### ISSUE TITLE
Wrong Type in README Sample Example

### ISSUE THREAD

**Issue by sjrothfuss** [alisterburt/torch-image-lerp#11]
* torch-image-lerp version: 0.0.3
* Python version: 3.10.14
* Operating System: macOS 14.5

### Description

Running the "Sample from image" code from the README gives an error due to unexpected datatype. Coercing the `image` dtype solves it.

### What I Did

```python
import torch
import numpy as np
from torch_image_lerp import sample_image_2d

image = torch.rand((28, 28))
coords = torch.tensor(np.random.uniform(low=0, high=27, size=(6, 7, 8, 2)))
samples = sample_image_2d(image=image, coordinates=coords)
```

```
RuntimeError: expected scalar type Float but found Double
```

Adding dtype to `image` as shown below prevents this error.

```python
image = torch.rand((28, 28), dtype=torch.float64)
```

**Comment by alisterburt** [comment]
Ah yeah - torch is much more annoying about dtypes than numpy, gotta make sure both match. Thanks for the ping - if you wanted to PR for the example that would be great

```python
coords = torch.tensor(np.random.uniform(low=0, high=27, size=(6, 7, 8, 2))).float()
```

is probably better 🙂
